### PR TITLE
Use a placeholder SLP if a SLP is missing

### LINKED ISSUE #8: Do not crash when a requested resource is missing
Scenario MUF7E5_1 requests `517.slp` (just a bit to the right of the  the bottom edge of the map) which doesn't exist in the shipped `GRAPHICS.DRS`.

This is a workaround until we learn how the Genie engine dealt with missing resources or find a better way to do it ourselves.

Perhaps the scenarios shipped on-disc weren't meant to be played in the retail product so this is just bogus data that was valid at one point in development.

### PR DESCRIPTION
**Pull request by Xinayder**
Fixes #8, for now.

### CODE REVIEW

File: crates/resource/src/shape_manager.rs [hunk 1]
```diff
@@ -198,10 +198,18 @@ impl ShapeManager {
 
         let slp_table = try!(drs_file.find_table(DrsFileType::Slp)
             .ok_or(ErrorKind::NoSlpTableInDrs(shape_key.drs_key)));
-        let slp_contents = try!(slp_table.find_file_contents(*shape_key.slp_id)
-            .ok_or(ErrorKind::SlpNotFound(shape_key.drs_key, *shape_key.slp_id)));
-
-        let slp = try!(SlpFile::read_from(&mut io::Cursor::new(slp_contents), *shape_key.player_color));
+        
+        let mut slp = SlpFile::new(0u8);
```
Comment (phrohdoh) [inline crates/resource/src/shape_manager.rs]: Instead of making this a `mut` local would you please do this:

```rust
let slp = match slp_table.find_file_contents(*shape_key.slp_id) { ... };
Shape::load_from(&slp, ...)
```

**Review by phrohdoh — CHANGES_REQUESTED** [review]
Left an inline change request.

File: crates/resource/src/shape_manager.rs [hunk 2]
```diff
@@ -198,10 +198,18 @@ impl ShapeManager {
...
+
+        match slp_table.find_file_contents(*shape_key.slp_id) {
+            Some(slp_contents) => {
+                slp = try!(SlpFile::read_from(&mut io::Cursor::new(slp_contents), *shape_key.player_color));
+            },
+            None => {
+                // Load the "missing" SLP file if we can't find the requested SLP in the DRS archive
+                slp = try!(SlpFile::read_from_file("data/nope.slp", *shape_key.player_color));
```
Comment (phrohdoh) [inline crates/resource/src/shape_manager.rs]: Also please rename this file to `nope-64x64.slp`.
